# The asn3 service provides a load-balancing proxy over the asn3-app
# pods. By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: asn3
spec:
  type: LoadBalancer
  selector:
    app: asn3
  ports:
  - port: 80
    targetPort: 8080